// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvNhPWzwL4TaEIEseag4VxX0XuCIuLSLo',
    appId: '1:614861377558:web:81cb8313a3437f37936537',
    messagingSenderId: '614861377558',
    projectId: 'security-cam-f322b',
    authDomain: 'security-cam-f322b.firebaseapp.com',
    storageBucket: 'security-cam-f322b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACAPB9s4nzxj1CMM4O6KBveBAs5cX5yCs',
    appId: '1:614861377558:android:055c23bcd1a4634f936537',
    messagingSenderId: '614861377558',
    projectId: 'security-cam-f322b',
    storageBucket: 'security-cam-f322b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZT7HAMmK7UTugs-CuqHOoBDY4sFyJFDU',
    appId: '1:614861377558:ios:e336fb6ef9af59de936537',
    messagingSenderId: '614861377558',
    projectId: 'security-cam-f322b',
    storageBucket: 'security-cam-f322b.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZT7HAMmK7UTugs-CuqHOoBDY4sFyJFDU',
    appId: '1:614861377558:ios:e336fb6ef9af59de936537',
    messagingSenderId: '614861377558',
    projectId: 'security-cam-f322b',
    storageBucket: 'security-cam-f322b.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvNhPWzwL4TaEIEseag4VxX0XuCIuLSLo',
    appId: '1:614861377558:web:200391096036a621936537',
    messagingSenderId: '614861377558',
    projectId: 'security-cam-f322b',
    authDomain: 'security-cam-f322b.firebaseapp.com',
    storageBucket: 'security-cam-f322b.firebasestorage.app',
  );
}
